FROM node:17.8-alpine AS BUILD-STAGE

WORKDIR /src

COPY . .
RUN npm install
RUN npm run build

FROM nginx:1.17-alpine AS DEPLOY-STAGE

COPY --from=BUILD-STAGE /src/dist/ /usr/share/nginx/html/
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]