version: "3.9"

services:
  # Postgres
  database:
    image: postgres:alpine
    env_file:
      - backend/.env

  # Backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/src
      - /dev/urandom:/dev/random
    ports:
      - "5000:5000"
    depends_on:
      - database
      - redis
    env_file:
      - backend/.env
      
  # Frontend
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/src
    ports:
      - "3000:3000"